name: Pre Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
 
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Pre Release ${{ github.event.inputs.version }}
        run: |
          java -version
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          ./gradlew release -Prelease.releaseVersion=${{ github.event.inputs.version }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./**/build/reports
